set -x
Checking for services in region: asia-east1
Checking for services in region: asia-northeast1
Checking for services in region: asia-northeast2
Checking for services in region: asia-northeast3
Checking for services in region: asia-south1
Checking for services in region: asia-southeast1
Checking for services in region: asia-southeast2
Checking for services in region: australia-southeast1
Checking for services in region: europe-central2
Checking for services in region: europe-north1
Checking for services in region: europe-west1
Checking for services in region: europe-west2
Checking for services in region: europe-west3
Checking for services in region: europe-west4
Checking for services in region: europe-west6
Checking for services in region: northamerica-northeast1
Checking for services in region: southamerica-east1
Checking for services in region: us-central1
Checking for services in region: us-east1
Checking for services in region: us-east4
Checking for services in region: us-west1
Checking for services in region: us-west2
Checking for services in region: us-west3
Checking for services in region: us-west4
Checking for repositories in region: africa-south1
Checking for repositories in region: asia
Checking for repositories in region: asia-east1
Checking for repositories in region: asia-east2
Checking for repositories in region: asia-northeast1
Checking for repositories in region: asia-northeast2
Checking for repositories in region: asia-northeast3
Checking for repositories in region: asia-south1
Checking for repositories in region: asia-south2
Checking for repositories in region: asia-southeast1
Checking for repositories in region: asia-southeast2
Checking for repositories in region: australia-southeast1
Checking for repositories in region: australia-southeast2
Checking for repositories in region: europe
Checking for repositories in region: europe-central2
Checking for repositories in region: europe-north1
Checking for repositories in region: europe-southwest1
Checking for repositories in region: europe-west1
Checking for repositories in region: europe-west10
Checking for repositories in region: europe-west12
Checking for repositories in region: europe-west2
Checking for repositories in region: europe-west3
Checking for repositories in region: europe-west4
Checking for repositories in region: europe-west6
Checking for repositories in region: europe-west8
Checking for repositories in region: europe-west9
Checking for repositories in region: me-central1
Checking for repositories in region: me-central2
Checking for repositories in region: me-west1
Checking for repositories in region: northamerica-northeast1
Checking for repositories in region: northamerica-northeast2
Checking for repositories in region: southamerica-east1
Deleting Artifact Registry repository: new in region southamerica-east1
Repository new deleted successfully.
Checking for repositories in region: southamerica-west1
Checking for repositories in region: us
Checking for repositories in region: us-central1
Checking for repositories in region: us-east1
Checking for repositories in region: us-east4
Checking for repositories in region: us-east5
Checking for repositories in region: us-south1
Checking for repositories in region: us-west1
Checking for repositories in region: us-west2
Checking for repositories in region: us-west3
Checking for repositories in region: us-west4
