name: 'coverage'
on:
  push:
    branches:
      - main
      - code-coverage
  workflow_dispatch:
jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      checks: 'write'
    steps:
      - uses: ArtiomTr/jest-coverage-report-action@v2
        env:
          GITHUB_TOKEN: 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
