name: 'coverage.'
on:
   # pull_request_target:
    push:   
        branches:
            - main
            - code-coverage
    workflow_dispatch:        
jobs:
    coverage:
        runs-on: ubuntu-latest
        permissions:
          contents: 'read'
          id-token: 'write'
          checks: 'write'
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
