name: 'coverage'
on:
    push:   
        branches:
            - main
            - code-coverage
    workflow_dispatch:        
jobs:
    coverage:
        runs-on: ubuntu-latest
        permissions:
          checks: write        
          issues: write 
          id-token: 'write'       
          pull-requests: read   
          contents: 'read'
          id-token: 'write'
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2